using System;
using System.Collections.Generic;

namespace AnalyzingPings
{
    class Server
    {
        /// <summary>
        /// Server is a class who contain the name and abreviation of all the country available 
        /// on the site 'https://public-dns.info/nameserver/'.
        /// This site contain a large adress of public dns all over the world.
        /// </summary>

        public Dictionary<string, string> Country = new Dictionary<string, string>()
        {
            {"Random","rd"},
            { "Albania", "al"},
            { "Algeria", "dz"},
            { "American Samoa", "as"},
            { "Andorra", "ad"},
            { "Angola", "ao"},
            { "Anguilla", "ai"},
            { "Antarctica", "aq"},
            { "Antigua and Barbuda", "ag"},
            { "Argentina", "ar"},
            { "Armenia", "am"},
            { "Australia", "au"},
            { "Austria", "at"},
            { "Azerbaijan", "az"},
            { "Bahamas", "bs"},
            { "Bahrain", "bh"},
            { "Bangladesh", "bd"},
            { "Barbados", "bb"},
            { "Belarus", "by"},
            { "Belgium", "be"},
            { "Belize", "bz"},
            { "Benin", "bj"},
            { "Bermuda", "bm"},
            { "Bhutan", "bt"},
            { "Bolivia", "bo"},
            { "Bosnia and Herzegovina", "ba"},
            { "Botswana", "bw"},
            { "Brazil", "br"},
            { "British Indian Ocean Territory", "io"},
            { "Brunei Darussalam", "bn"},
            { "Bulgaria", "bg"},
            { "Burundi", "bi"},
            { "Cambodia", "kh"},
            { "Cameroon", "cm"},
            { "Canada", "ca"},
            { "Cape Verde", "cv"},
            { "Cayman Islands", "ky"},
            { "Chile", "cl"},
            { "China", "cn"},
            { "Colombia", "co"},
            { "Cook Islands", "ck"},
            { "Costa Rica", "cr"},
            { "Croatia", "hr"},
            { "Cuba", "cu"},
            { "Cyprus", "cy"},
            { "Czech Republic", "cz"},
            { "Côte d'Ivoire", "ci"},
            { "Denmark", "dk"},
            { "Djibouti", "dj"},
            { "Dominica", "dm"},
            {"Dominican Republic", "do"},
            {"Ecuador", "ec"},
            {"Egypt", "eg"},
            {"El Salvador", "sv"},
            {"Equatorial Guinea", "gq"},
            {"Estonia", "ee"},
            {"Ethiopia", "et"},
            {"Fiji", "fj"},
            {"Finland", "fi"},
            {"France", "fr"},
            {"French Polynesia", "pf"},
            {"Gabon", "ga"},
            {"Gambia", "gm"},
            {"Georgia", "ge"},
            {"Germany", "de"},
            {"Ghana", "gh"},
            {"Greece", "gr"},
            {"Greenland", "gl"},
            {"Grenada", "gd"},
            {"Guadeloupe", "gp"},
            {"Guam", "gu"},
            {"Guatemala", "gt"},
            {"Guinea", "gn"},
            {"Guyana", "gy"},
            {"Haiti", "ht"},
            {"Honduras", "hn"},
            {"Hong Kong", "hk"},
            {"Hungary", "hu"},
            {"Iceland", "is"},
            {"India", "in"},
            {"Indonesia", "id"},
            {"Ireland", "ie"},
            {"Israel", "il"},
            {"Italy", "it"},
            {"Jamaica", "jm"},
            {"Japan", "jp"},
            {"Jordan", "jo"},
            {"Kazakhstan", "kz"},
            {"Kenya", "ke"},
            {"Kuwait", "kw"},
            {"Kyrgyzstan", "kg"},
            {"Lao People's Democratic Republic", "la"},
            {"Latvia", "lv"},
            {"Lebanon", "lb"},
            {"Liberia", "lr"},
            {"Liechtenstein", "li"},
            {"Lithuania", "lt"},
            {"Luxembourg", "lu"},
            {"Macao", "mo"},
            {"Macedonia", "mk"},
            {"Malawi", "mw"},
            {"Malaysia", "my"},
            {"Maldives", "mv"},
            {"Malta", "mt"},
            {"Marshall Islands", "mh"},
            {"Martinique", "mq"},
            {"Mauritania", "mr"},
            {"Mauritius", "mu"},
            {"Mexico", "mx"},
            {"Micronesia", "fm"},
            {"Moldova", "md"},
            {"Monaco", "mc"},
            {"Mongolia", "mn"},
            {"Morocco", "ma"},
            {"Mozambique", "mz"},
            {"Myanmar", "mm"},
            {"Namibia", "na"},
            {"Nauru", "nr"},
            {"Nepal", "np"},
            {"Netherlands", "nl"},
            {"New Caledonia", "nc"},
            {"New Zealand", "nz"},
            {"Nicaragua", "ni"},
            {"Nigeria", "ng"},
            {"Niue", "nu"},
            {"Norway", "no"},
            {"Panama", "pa"},
            {"Papua New Guinea", "pg"},
            {"Paraguay", "py"},
            {"Peru", "pe"},
            {"Philippines", "ph"},
            {"Poland", "pl"},
            {"Portugal", ""},
            {"Puerto Rico", "pr"},
            {"Qatar", "qa"},
            {"Romania", "ro"},
            {"Russian Federation", "ru"},
            {"Réunion", "re"},
            {"Saint Kitts and Nevis", "kn"},
            {"Saint Lucia", "lc"},
            {"Saint Pierre and Miquelon", "pm"},
            {"Saint Vincent and the Grenadines", "vc"},
            {"Samoa", "ws"},
            {"Sao Tome and Principe", "st"},
            {"Saudi Arabia", "sa"},
            {"Senegal", "sn"},
            {"Seychelles", "sc"},
            {"Singapore", "sg"},
            {"Slovakia", "sk"},
            {"Slovenia", "si"},
            {"South Africa", "za"},
            {"Spain", "es"},
            {"Sri Lanka", "lk"},
            {"Sudan", "sd"},
            {"Suriname", "sr"},
            {"Swaziland", "sz"},
            {"Sweden", "se"},
            {"Switzerland", "ch"},
            {"Taiwan, Province of China", "tw"},
            {"Tajikistan", "tj"},
            {"Tanzania", "tz"},
            {"Thailand", "th"},
            {"Togo", "tg"},
            {"Tonga", "to"},
            {"Trinidad and Tobago", "tt"},
            {"Tunisia", "tn"},
            {"Ukraine", "ua"},
            {"United Arab Emirates", "ae"},
            {"United Kingdom", "gb"},
            {"United States", "us"},
            {"Uruguay", "uy"},
            {"Uzbekistan", "uz"},
            {"Vanuatu", "vu"},
            {"Venezuela", "ve"},
            {"Viet Nam", "vn"},
            {"Virgin Islands, British", "vg"},
            {"Virgin Islands, U.S.", "vi"},
            {"Wallis and Futuna", "wf"},
            {"Yemen", "ye"},
            {"Zambia", "zm"},
            {"Zimbabwe","zw"}
    };


        public string base_url = "https://public-dns.info/nameserver/";

        public string selectedCounrty = null;

        /// <summary>
        /// Method to select a random Country from the dictionnary.
        /// </summary>
        public string GetRandomCountry(List<string> Country)
        {
            Random r = new Random();
            int index = r.Next(Country.Count);
            string randomCountry = Country[index];
            return randomCountry;
        }
    }
}
